import fs from 'fs';
import path from 'path';

export interface CodeAnalysis {
  components: { name: string; props: string[]; purpose: string }[];
  services: { name: string; responsibility: string }[];
  apiRoutes: { method: string; path: string; description: string }[];
  models: { name: string; relationships: string[] }[];
}

export function analyzeCode(filePath: string, content: string): CodeAnalysis {
  const result: CodeAnalysis = {
    components: [],
    services: [],
    apiRoutes: [],
    models: [],
  };

  // Extract React components (capitalized function/const exports)
  const componentRegex =
    /export\s+(?:default\s+)?(?:function|const)\s+([A-Z][a-zA-Z0-9]*)\s*(?:\([^)]*\)|(?:=\s*(?:async\s*)?\())/g;
  const seenComponents = new Set<string>();
  let match;
  while ((match = componentRegex.exec(content)) !== null) {
    const name = match[1];
    if (seenComponents.has(name)) continue;
    // Skip if it's actually a service/class-like name
    if (/Service|Controller|Manager|Handler|Repository/.test(name)) continue;
    seenComponents.add(name);
    const propsMatch = content.match(
      new RegExp(`function\\s+${name}\\s*\\(\\{([^}]*)\\}`)
    );
    const props = propsMatch
      ? propsMatch[1]
          .split(',')
          .map((p) => p.trim().split(':')[0].trim())
          .filter(Boolean)
      : [];
    result.components.push({ name, props, purpose: `${name} UI component` });
  }

  // Extract classes (services, managers, controllers, etc.)
  const classRegex = /(?:export\s+)?(?:export\s+default\s+)?class\s+([A-Za-z][a-zA-Z0-9]*)/g;
  const seenServices = new Set<string>();
  while ((match = classRegex.exec(content)) !== null) {
    const name = match[1];
    if (seenServices.has(name)) continue;
    seenServices.add(name);
    const baseName = name
      .replace(/Service$/, '')
      .replace(/Controller$/, '')
      .replace(/Manager$/, '')
      .replace(/Handler$/, '')
      .replace(/Repository$/, '');
    result.services.push({
      name,
      responsibility: `Handles ${baseName} operations`,
    });
  }

  // Extract API routes — Next.js route handlers and Express-style
  const routePatterns: RegExp[] = [
    /(?:app|router)\.(get|post|put|patch|delete)\s*\(\s*['"`]([^'"`]+)['"`]/gi,
    /export\s+(?:async\s+)?function\s+(GET|POST|PUT|PATCH|DELETE)\s*\(/g,
    /export\s+const\s+(GET|POST|PUT|PATCH|DELETE)\s*=/g,
  ];

  const seenRoutes = new Set<string>();
  for (const pattern of routePatterns) {
    while ((match = pattern.exec(content)) !== null) {
      const method = match[1].toUpperCase();
      const routePath =
        match[2] ||
        filePath
          .replace(/.*app/, '')
          .replace(/\/route\.(ts|tsx|js|jsx)$/, '')
          .replace(/\\/g, '/') ||
        '/api/unknown';
      const key = `${method}:${routePath}`;
      if (seenRoutes.has(key)) continue;
      seenRoutes.add(key);
      result.apiRoutes.push({
        method,
        path: routePath,
        description: `${method} ${routePath}`,
      });
    }
  }

  // Extract interfaces/types as models
  const modelRegex =
    /(?:^|\n)(?:export\s+)?(?:interface|type)\s+([A-Z][a-zA-Z0-9]*)\s*(?:extends\s+[A-Za-z<>,\s]+)?\{/g;
  const seenModels = new Set<string>();
  while ((match = modelRegex.exec(content)) !== null) {
    const name = match[1];
    if (seenModels.has(name)) continue;
    if (['Props', 'State', 'Config', 'Options', 'Params', 'Dto'].some((s) => name.endsWith(s)))
      continue;
    seenModels.add(name);
    result.models.push({ name, relationships: [] });
  }

  return result;
}

export function generateArchitectureDocs(analyses: Map<string, CodeAnalysis>): string {
  const lines: string[] = [
    '# Architecture Documentation',
    '',
    `> Auto-generated by ArchitectAI Hook on ${new Date().toLocaleString()}`,
    '',
    '---',
    '',
  ];

  let hasContent = false;

  analyses.forEach((analysis, filePath) => {
    const fileName = path.basename(filePath, path.extname(filePath));

    analysis.services.forEach((svc) => {
      hasContent = true;
      lines.push(`## ⚙️ ${svc.name}`);
      lines.push('');
      lines.push(`**File:** \`${filePath}\``);
      lines.push('');
      lines.push(`**Responsibility:** ${svc.responsibility}`);
      lines.push('');
      lines.push('**Dependencies:**');
      lines.push('- Database');
      lines.push('- External APIs');
      lines.push('');
    });

    analysis.components.forEach((comp) => {
      hasContent = true;
      lines.push(`## 🧩 ${comp.name}`);
      lines.push('');
      lines.push(`**File:** \`${filePath}\``);
      lines.push('');
      lines.push(`**Type:** React Component`);
      lines.push('');
      if (comp.props.length > 0) {
        lines.push('**Props:**');
        comp.props.forEach((p) => lines.push(`- \`${p}\``));
        lines.push('');
      }
    });

    analysis.models.forEach((model) => {
      hasContent = true;
      lines.push(`## 📦 ${model.name} Model`);
      lines.push('');
      lines.push(`**File:** \`${filePath}\``);
      lines.push('');
    });
  });

  if (!hasContent) {
    lines.push('## Overview');
    lines.push('');
    lines.push('No services or components detected yet.');
    lines.push('');
    lines.push('Save a file in `src/`, `app/`, or `components/` to trigger analysis.');
  }

  return lines.join('\n');
}

export function generateApiDocs(analyses: Map<string, CodeAnalysis>): string {
  const lines: string[] = [
    '# API Documentation',
    '',
    `> Auto-generated by ArchitectAI Hook on ${new Date().toLocaleString()}`,
    '',
    '---',
    '',
  ];

  let hasRoutes = false;
  analyses.forEach((analysis) => {
    analysis.apiRoutes.forEach((route) => {
      hasRoutes = true;
      lines.push(`## ${route.method} \`${route.path}\``);
      lines.push('');
      lines.push(`**Description:** ${route.description}`);
      lines.push('');
      lines.push('**Request Body:**');
      lines.push('```json');
      lines.push('{');
      if (route.method === 'POST' || route.method === 'PUT' || route.method === 'PATCH') {
        lines.push('  "field": "value"');
      }
      lines.push('}');
      lines.push('```');
      lines.push('');
      lines.push('**Response:**');
      lines.push('```json');
      lines.push('{');
      lines.push('  "success": true,');
      lines.push('  "data": {}');
      lines.push('}');
      lines.push('```');
      lines.push('');
      lines.push('**Status Codes:**');
      lines.push('- `200` — Success');
      lines.push('- `400` — Bad Request');
      lines.push('- `401` — Unauthorized');
      lines.push('- `500` — Internal Server Error');
      lines.push('');
    });
  });

  if (!hasRoutes) {
    lines.push('No API routes detected yet.');
    lines.push('');
    lines.push('Add route handlers in `app/api/` or `src/` to see API docs here.');
  }

  return lines.join('\n');
}

export function generateMermaidDiagram(analyses: Map<string, CodeAnalysis>): string {
  const lines: string[] = ['graph TD'];
  lines.push('');
  lines.push('  User["👤 User"]');
  lines.push('  Frontend["⚛️ Frontend"]');
  lines.push('  API["🔌 API Layer"]');
  lines.push('  User --> Frontend');
  lines.push('  Frontend --> API');

  const addedNodes = new Set<string>(['User', 'Frontend', 'API', 'Database']);
  let hasExtras = false;

  analyses.forEach((analysis) => {
    analysis.services.forEach((svc) => {
      const id = svc.name.replace(/\W+/g, '_');
      if (addedNodes.has(id)) return;
      addedNodes.add(id);
      hasExtras = true;
      lines.push(`  ${id}["⚙️ ${svc.name}"]`);
      lines.push(`  API --> ${id}`);
      if (!addedNodes.has('Database')) {
        addedNodes.add('Database');
      }
      lines.push(`  ${id} --> Database[("🗄️ Database")]`);
    });

    analysis.components.forEach((comp) => {
      const id = comp.name.replace(/\W+/g, '_');
      if (addedNodes.has(id)) return;
      addedNodes.add(id);
      hasExtras = true;
      lines.push(`  ${id}["🧩 ${comp.name}"]`);
      lines.push(`  Frontend --> ${id}`);
    });
  });

  if (!hasExtras) {
    lines.push('  Docs["📄 Auto-Generated Docs"]');
    lines.push('  API --> Docs');
  }

  return lines.join('\n');
}

export function generateChangelog(
  entries: { timestamp: string; filePath: string; analysis: CodeAnalysis }[]
): string {
  const grouped: Record<string, string[]> = {};

  entries.forEach(({ timestamp, filePath, analysis }) => {
    const date = timestamp.split('T')[0];
    if (!grouped[date]) grouped[date] = [];

    const fileName = path.basename(filePath, path.extname(filePath));
    analysis.components.forEach((c) =>
      grouped[date].push(`- Updated \`${c.name}\` component in \`${fileName}\``)
    );
    analysis.services.forEach((s) =>
      grouped[date].push(`- Updated \`${s.name}\` in \`${fileName}\``)
    );
    analysis.apiRoutes.forEach((r) =>
      grouped[date].push(`- Updated \`${r.method} ${r.path}\` endpoint`)
    );
    if (
      analysis.components.length === 0 &&
      analysis.services.length === 0 &&
      analysis.apiRoutes.length === 0
    ) {
      grouped[date].push(`- Modified \`${fileName}\``);
    }
  });

  const lines: string[] = [
    '# Changelog',
    '',
    '> Auto-generated by ArchitectAI Hook',
    '',
    '---',
    '',
  ];

  Object.entries(grouped)
    .sort(([a], [b]) => b.localeCompare(a))
    .forEach(([date, changes]) => {
      lines.push(`## ${date}`);
      lines.push('');
      [...new Set(changes)].forEach((c) => lines.push(c));
      lines.push('');
    });

  if (Object.keys(grouped).length === 0) {
    lines.push('No changes recorded yet.');
  }

  return lines.join('\n');
}

export function generateTestingRecommendations(
  analyses: Map<string, CodeAnalysis>
): string {
  const lines: string[] = [
    '# Testing Recommendations',
    '',
    '> Auto-generated by ArchitectAI Hook',
    '',
    '---',
    '',
  ];

  let hasContent = false;

  analyses.forEach((analysis) => {
    analysis.services.forEach((svc) => {
      hasContent = true;
      lines.push(`## ⚙️ ${svc.name}`);
      lines.push('');
      lines.push('**Unit Tests:**');
      lines.push(`- ✅ Happy path — successful operation`);
      lines.push(`- ❌ Validation failure — invalid input`);
      lines.push(`- ❌ Database connection failure`);
      lines.push(`- ❌ Duplicate entry handling`);
      lines.push(`- ⚠️ Edge cases and boundary conditions`);
      lines.push('');
    });

    analysis.apiRoutes.forEach((route) => {
      hasContent = true;
      lines.push(`## 🔌 ${route.method} ${route.path}`);
      lines.push('');
      lines.push('**Integration Tests:**');
      lines.push(`- ✅ 200 Success response`);
      lines.push(`- ❌ 400 Invalid request body`);
      lines.push(`- ❌ 401 Unauthorized`);
      lines.push(`- ❌ 500 Internal server error`);
      lines.push(`- ⚠️ Rate limiting`);
      lines.push('');
    });

    analysis.components.forEach((comp) => {
      hasContent = true;
      lines.push(`## 🧩 ${comp.name} Component`);
      lines.push('');
      lines.push('**Component Tests:**');
      lines.push(`- ✅ Renders without errors`);
      lines.push(`- ✅ Renders with all props`);
      lines.push(`- ❌ Handles missing/undefined props gracefully`);
      lines.push(`- ⚠️ Accessibility (a11y) compliance`);
      lines.push('');
    });
  });

  if (!hasContent) {
    lines.push('No code analyzed yet.');
    lines.push('');
    lines.push('Save files in `src/` to get testing recommendations.');
  }

  return lines.join('\n');
}

export function saveDocs(
  basePath: string,
  docs: {
    architecture: string;
    apiDocs: string;
    changelog: string;
    testing: string;
    diagram: string;
  }
) {
  const docsDir = path.join(basePath, 'docs');
  if (!fs.existsSync(docsDir)) fs.mkdirSync(docsDir, { recursive: true });

  fs.writeFileSync(path.join(docsDir, 'architecture.md'), docs.architecture, 'utf-8');
  fs.writeFileSync(path.join(docsDir, 'api.md'), docs.apiDocs, 'utf-8');
  fs.writeFileSync(path.join(docsDir, 'changelog.md'), docs.changelog, 'utf-8');
  fs.writeFileSync(path.join(docsDir, 'testing.md'), docs.testing, 'utf-8');
  fs.writeFileSync(path.join(docsDir, 'system-diagram.mmd'), docs.diagram, 'utf-8');
}

export function loadDocs(basePath: string) {
  const docsDir = path.join(basePath, 'docs');
  const read = (file: string) => {
    try {
      return fs.readFileSync(path.join(docsDir, file), 'utf-8');
    } catch {
      return '';
    }
  };
  return {
    architecture: read('architecture.md'),
    apiDocs: read('api.md'),
    changelog: read('changelog.md'),
    testing: read('testing.md'),
    diagram: read('system-diagram.mmd'),
  };
}
